config/routes.rb
Rails.application.routes.draw do
  resources :log_views

   resources :log_views do
      member do
        get 'generate_report'
        
      end
  end

  resources :projects
  resources :accounts

  root "home#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
	has_many :projects

	def self.search(search)
	  where("account_name LIKE ?", "%#{search}%")
	end
end
	

app/models/log_type.rb
class LogType < ActiveRecord::Base
	has_many :log_views
end

app/models/log_view.rb
class LogView < ActiveRecord::Base
	belongs_to :project
	belongs_to :log_type
	mount_uploader :log_file, LogFileUploader # Tells rails to use this uploader for this model.
	def self.search(project_id, log_type_id)
		  if project_id.present? &&  log_type_id.present?
		  	where("project_id = ? AND log_type_id = ? ", project_id , log_type_id) 
		  elsif project_id.present?
		  	where("project_id = ? ", project_id) 
		  elsif log_type_id.present?
		  	where("log_type_id = ? ", log_type_id)	
		  end	
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :account
	has_many :log_views
	def self.search(search)
	  where("project_name LIKE ?", "%#{search}%")
	end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    #@accounts = Account.all
    if params[:search] && params[:commit] !='Reset'
      @accounts = Account.search(params[:search]).order("created_at DESC")
    elsif params[:commit] =='Reset'
       redirect_to :accounts
    else
       @accounts = Account.all.order('created_at DESC')
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:account_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/log_views_controller.rb
class LogViewsController < ApplicationController
  before_action :set_log_view, only: [:show, :edit, :update, :destroy, :generate_report]

  # GET /log_views
  # GET /log_views.json
  def index
    if params[:commit] =='Search' && (params[:log_view][:project_id].present? || params[:log_view][:log_type_id].present?)    
      @log_views = LogView.search(params[:log_view][:project_id],params[:log_view][:log_type_id]).order("created_at DESC")
    elsif params[:commit] =='Reset'
      redirect_to :log_views
    else
       @log_views = LogView.all.order('created_at DESC')
    end 
  end

  # GET /log_views/1
  # GET /log_views/1.json
  def show
  end

  # GET /log_views/new
  def new
    @log_view = LogView.new
  end

  # GET /log_views/1/edit
  def edit
  end

  # POST /log_views
  # POST /log_views.json
  def create
    @log_view = LogView.new(log_view_params)

    respond_to do |format|
      if @log_view.save
        format.html { redirect_to @log_view, notice: 'Log view was successfully created.' }
        format.json { render :show, status: :created, location: @log_view }
      else
        format.html { render :new }
        format.json { render json: @log_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /log_views/1
  # PATCH/PUT /log_views/1.json
  def update
    respond_to do |format|
      if @log_view.update(log_view_params)
        format.html { redirect_to @log_view, notice: 'Log view was successfully updated.' }
        format.json { render :show, status: :ok, location: @log_view }
      else
        format.html { render :edit }
        format.json { render json: @log_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_views/1
  # DELETE /log_views/1.json
  def destroy
    @log_view.destroy
    respond_to do |format|
      format.html { redirect_to log_views_url, notice: 'Log view was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_report
    @log_view.update(is_report_generated: true)
    respond_to do |format|
      format.html { redirect_to log_views_url, notice: 'Report generated successfully' }
      format.json { head :no_content }
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_view
      @log_view = LogView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_view_params
      params.require(:log_view).permit(:project_id, :log_type_id, :log_file, :is_report_generated)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    #@projects = Project.all
    if params[:search] && params[:commit] !='Reset'
      @projects = Project.search(params[:search]).order("created_at DESC")
    elsif params[:commit] =='Reset'
       redirect_to :projects
    else
       @projects = Project.all.order('created_at DESC')
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @account = Account.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/log_views_helper.rb
module LogViewsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => "form-horizontal account" } do |f| %>

  <% if @account.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :account_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :account_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:account_name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:account_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

<div><%= form_tag(accounts_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
<%= submit_tag "Search" ,:class => 'btn btn-xs btn-info'%> <%= submit_tag "Reset",:class => 'btn btn-xs btn-info' %>
<p>&nbsp;</p>
</div>
<% end %>
  <tbody>
   <% if @accounts.present? %>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.id, account_path(account) %></td>
        <td><%= account.account_name %></td>
        <td><%=l account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end
    else %>
      <tr><td>
      There are no accounts containing the term(s) <%= params[:search] %>.</td> </tr>
    <% end %>

  </tbody>
</table>
<% if !params[:search]%>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_account_path,
            :class => 'btn btn-primary' %>
<% end%>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:account_name) %>:</strong></dt>
  <dd><%= @account.account_name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application-bk.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LogManagement" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">LogManagement</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", :root %></li>
            <li><%= link_to "Account", :accounts  %></li>
            <li><%= link_to "Project", :projects  %></li>
            <li><%= link_to "Log View", :log_views  %></li>
           
            <li><%= link_to "Reports", "/path3"  %></li>
            <li><%= link_to "Help", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!-- <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> --><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&nbsp;</p>
        <p align="center">Copyright &copy; 2016 NTTDATA Global Delivery Service Private Limited. All Rights Reserved.</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/log_views/_form.html.erb
<%= form_for @log_view, :html => { :class => "form-horizontal log_view", multipart: true } do |f| %>

  <% if @log_view.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@log_view.errors.count, "error") %> prohibited this log_view from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @log_view.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%#= f.text_field :project_id, :class => 'form-control' %>
    <%= select("log_view", "project_id", Project.all.collect {|p| [ p.project_name, p.id ] }, {include_blank: 'Select'},:class => 'form-control' )%>
    </div>
    <%=f.error_span(:project_id) %>
  </div>
  <div class="form-group">
    <%= f.label :log_type_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%#= f.text_field :log_type_id, :class => 'form-control' %>
      <%= select("log_view", "log_type_id", LogType.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Select'},:class => 'form-control' )%>
    </div>
    <%=f.error_span(:log_type_id) %>
  </div>
  <div class="form-group">
    <%= f.label :log_file, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :log_file %>
    </div>
    <%=f.error_span(:log_file) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                log_views_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/log_views/edit.html.erb
<%- model_class = LogView -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/log_views/index.html.erb
<%- model_class = LogView -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:log_type_id) %></th>
      <th><%= model_class.human_attribute_name(:log_file) %></th>
       <th><%=  "Generate Report"%></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    
    <div><%= form_tag(log_views_path, :method => "get", id: "search-form") do %>

      <%#= select("log_view", "log_type_id", LogType.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'Log Type'}, {:selected => params[:log_view][:log_type_id].to_s} )%>
       <% 
        if params.has_key?(:log_view) && params[:log_view][:log_type_id].present?

        %>
            <%= select("log_view", "log_type_id", 
  options_from_collection_for_select(LogType.all, :id, :name, params[:log_view][:log_type_id].to_i) , include_blank: 'Log Type' )%>
        <%
        else
        %>
            <%= select("log_view", "log_type_id", 
  options_from_collection_for_select(LogType.all, :id, :name) , include_blank: 'Log Type' )%>
        <%
        end
        if params.has_key?(:log_view) && params[:log_view][:project_id].present?
        %>
         <%= select("log_view", "project_id", 
  options_from_collection_for_select(Project.all, :id, :project_name, params[:log_view][:project_id].to_i) , include_blank: 'Project' )%>
        <%
        else
          %>
            <%= select("log_view", "project_id", 
  options_from_collection_for_select(Project.all, :id, :project_name) , include_blank: 'Project' )%>
       <% end
       %>
      
  <%#= collection_select(:log_view, :project_id, Project.all, :id, :project_name, {include_blank: 'Project'},{:selected=> params[:log_view][:project_id].to_s})%>
  
  <%#= text_field_tag :project_id, params[:project_id], placeholder: "Select Project" %>
  <%#= text_field_tag :log_type, params[:log_type], placeholder: "Select Log Type" %>
  <%= submit_tag "Search" ,:class => 'btn btn-xs btn-info'%> <%= submit_tag "Reset",:class => 'btn btn-xs btn-info' %>
  <p>&nbsp;</p>
</div>
<% end %>
  <% if @log_views.present? %>
    <% @log_views.each do |log_view| %> 
      <tr>
        <td><%= link_to log_view.id, log_view_path(log_view) %></td>
        <td><%= log_view.project.project_name %></td>
        <td><%= log_view.log_type.name %></td>
        <td><%= link_to "Download File", log_view.log_file_url %></td>
         <% if log_view.is_report_generated%>
        <td><button type="button" class="btn btn-info">View Report</button></td>
        <% else %>
        <td> <%= link_to t('.generate_report', :default => t("helpers.links.generate_report")),
                      generate_report_log_view_path(log_view), :class => 'btn btn-info btn-xs' %></td>
        <% end%>
        <td><%=l log_view.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_log_view_path(log_view), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      log_view_path(log_view),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end else %>
    <tr><td>
    There are no log view containing the term(s)</td> </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_log_view_path,
            :class => 'btn btn-primary' %>

app/views/log_views/new.html.erb
<%- model_class = LogView -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/log_views/show.html.erb
<%- model_class = LogView -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @log_view.project_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:log_type_id) %>:</strong></dt>
  <dd><%= @log_view.log_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:log_file) %>:</strong></dt>
  <dd><%= @log_view.log_file %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              log_views_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_log_view_path(@log_view), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              log_view_path(@log_view),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:project_name) %></th>
      <th><%= model_class.human_attribute_name(:account_id) %></th>
     
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
  <div><%= form_tag(projects_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
  <%= submit_tag "Search" ,:class => 'btn btn-xs btn-info'%> <%= submit_tag "Reset",:class => 'btn btn-xs btn-info' %>
  <p>&nbsp;</p>
  </div>
  <% end %>
   <% if @projects.present? %>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.project_name %></td>
        <td><%= project.account.account_name %></td>       
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end else %>
    <tr><td>
    There are no projects containing the term(s) <%= params[:search] %>.</td> </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>